# Generated by Django 2.0.5 on 2018-06-19 07:47

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApiData',
            fields=[
                ('appid', models.AutoField(primary_key=True, serialize=False)),
                ('apikey', models.CharField(max_length=100)),
                ('apVersion', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Api Key',
                'db_table': '"apidata"',
                'ordering': ('created',),
            },
        ),
        migrations.CreateModel(
            name='PhotoData',
            fields=[
                ('photoid', models.AutoField(primary_key=True, serialize=False)),
                ('imageobject', models.ImageField(blank=True, null=True, upload_to='venues/%Y/%m/')),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Venue Pictures',
                'db_table': '"photodata"',
                'ordering': ('created',),
            },
        ),
        migrations.CreateModel(
            name='TokenData',
            fields=[
                ('tokenid', models.AutoField(primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('expiry', models.DateTimeField()),
            ],
            options={
                'verbose_name_plural': 'Tokens',
                'db_table': '"tokendata"',
                'ordering': ('created',),
            },
        ),
        migrations.CreateModel(
            name='UseraccountData',
            fields=[
                ('userid', models.AutoField(primary_key=True, serialize=False)),
                ('fullname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=15)),
                ('phonenumber', models.CharField(blank=True, max_length=15)),
                ('apikey', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'User Accounts',
                'db_table': '"useraccountdata"',
                'ordering': ('fullname',),
            },
        ),
        migrations.CreateModel(
            name='VenueData',
            fields=[
                ('venueid', models.AutoField(primary_key=True, serialize=False)),
                ('googleplacesId', models.CharField(blank=True, max_length=100)),
                ('foursquareplacesId', models.CharField(blank=True, max_length=100)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('type', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, size=None)),
                ('loc_lat', models.CharField(blank=True, max_length=20)),
                ('loc_lng', models.CharField(blank=True, max_length=20)),
                ('streetname', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('postcode', models.CharField(max_length=100)),
                ('vicinity', models.CharField(blank=True, max_length=100)),
                ('icon', models.CharField(blank=True, max_length=100)),
                ('open_now', models.BooleanField(default=False)),
                ('open_periods', django.contrib.postgres.fields.jsonb.JSONField()),
                ('website', models.CharField(blank=True, max_length=200)),
                ('phonenumber', models.CharField(max_length=20)),
                ('price_level', models.CharField(choices=[('0', 'FREE'), ('1', 'INEXPENSIVE'), ('2', 'MODERATE'), ('3', 'EXPENSIVE'), ('4', 'VERY EXPENSIVE')], default='0', max_length=1)),
                ('rating', models.CharField(blank=True, max_length=4)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Venues',
                'db_table': '"venuedata"',
                'ordering': ('created',),
            },
        ),
        migrations.AddField(
            model_name='tokendata',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restapi.UseraccountData'),
        ),
        migrations.AddField(
            model_name='photodata',
            name='venue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restapi.VenueData'),
        ),
    ]
