# Generated by Django 2.0.7 on 2018-10-01 14:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mood',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0.1)]),
        ),
    ]
