# Generated by Django 2.0.7 on 2018-07-30 09:44

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0002_auto_20180620_2119'),
    ]

    operations = [
        migrations.AddField(
            model_name='venuedata',
            name='description',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='venuedata',
            name='menu',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={'Coffe': 'null'}),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='venuedata',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='venuedata',
            name='price_level',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
