# Generated by Django 2.0.7 on 2018-07-30 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0003_auto_20180730_1144'),
    ]

    operations = [
        migrations.RenameField(
            model_name='venuedata',
            old_name='price_level',
            new_name='price_start',
        ),
    ]
