# Generated by Django 2.0.7 on 2018-08-09 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0004_auto_20180730_1146'),
    ]

    operations = [
        migrations.RenameField(
            model_name='venuedata',
            old_name='foursquareplacesId',
            new_name='OSMID',
        ),
        migrations.RenameField(
            model_name='venuedata',
            old_name='icon',
            new_name='neighborhood',
        ),
        migrations.RemoveField(
            model_name='venuedata',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='venuedata',
            name='vicinity',
        ),
        migrations.AddField(
            model_name='venuedata',
            name='capacity',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='venuedata',
            name='email',
            field=models.EmailField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='venuedata',
            name='hits',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='venuedata',
            name='micro_brewery',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='venuedata',
            name='outdoorsitting',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='venuedata',
            name='smookingavailability',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='venuedata',
            name='wheelchairaval',
            field=models.BooleanField(default=False),
        ),
    ]
