# Generated by Django 2.0.7 on 2018-08-17 10:00

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0006_auto_20180809_1027'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityData',
            fields=[
                ('activityid', models.AutoField(primary_key=True, serialize=False, verbose_name='Photo ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('subtitle', models.CharField(max_length=100, verbose_name='Sub Title')),
                ('image', models.ImageField(blank=True, null=True, upload_to='venues/%Y/%m/', verbose_name='Image')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
            ],
            options={
                'verbose_name_plural': 'Activities',
                'db_table': '"activitydata"',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='MenuData',
            fields=[
                ('menuid', models.AutoField(primary_key=True, serialize=False, verbose_name='Menu ID')),
                ('name', models.CharField(max_length=100, verbose_name='Menu Name')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
            ],
            options={
                'verbose_name_plural': 'Menu Types',
                'db_table': '"menudata"',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='OpenHours',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.CharField(max_length=20, verbose_name='Day of week')),
                ('open', models.TimeField(blank=True, verbose_name='Open time')),
                ('closed', models.TimeField(blank=True, verbose_name='Closing time')),
                ('open_alt', models.TimeField(blank=True, verbose_name='Alt open time')),
                ('closed_alt', models.TimeField(blank=True, verbose_name='Alt closing time')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
            ],
            options={
                'verbose_name_plural': 'Opening hours',
                'db_table': '"openhours"',
                'ordering': ('venue',),
            },
        ),
        migrations.CreateModel(
            name='VenueTypeData',
            fields=[
                ('venuetypeid', models.AutoField(primary_key=True, serialize=False, verbose_name='Venue type ID')),
                ('description', models.CharField(max_length=100, verbose_name='Description')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
            ],
            options={
                'verbose_name_plural': 'Venue Type',
                'db_table': '"venuetypedata"',
                'ordering': ('description',),
            },
        ),
        migrations.RemoveField(
            model_name='photodata',
            name='imageobject',
        ),
        migrations.AddField(
            model_name='photodata',
            name='back_image',
            field=models.ImageField(blank=True, null=True, upload_to='venues/%Y/%m/', verbose_name='Background Image'),
        ),
        migrations.AddField(
            model_name='photodata',
            name='fore_image',
            field=models.ImageField(blank=True, null=True, upload_to='venues/%Y/%m/', verbose_name='Profile Gallery'),
        ),
        migrations.AlterField(
            model_name='apidata',
            name='apVersion',
            field=models.CharField(max_length=100, verbose_name='API Version'),
        ),
        migrations.AlterField(
            model_name='apidata',
            name='apikey',
            field=models.CharField(max_length=100, verbose_name='API Key'),
        ),
        migrations.AlterField(
            model_name='apidata',
            name='appid',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='API Id'),
        ),
        migrations.AlterField(
            model_name='apidata',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date Created'),
        ),
        migrations.AlterField(
            model_name='photodata',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date Created'),
        ),
        migrations.AlterField(
            model_name='photodata',
            name='height',
            field=models.IntegerField(verbose_name='Image height'),
        ),
        migrations.AlterField(
            model_name='photodata',
            name='photoid',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Photo ID'),
        ),
        migrations.AlterField(
            model_name='photodata',
            name='width',
            field=models.IntegerField(verbose_name='Image width'),
        ),
        migrations.AlterField(
            model_name='tokendata',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date Created'),
        ),
        migrations.AlterField(
            model_name='tokendata',
            name='expiry',
            field=models.DateTimeField(verbose_name='Expiring Date'),
        ),
        migrations.AlterField(
            model_name='tokendata',
            name='token',
            field=models.CharField(max_length=100, verbose_name='Token'),
        ),
        migrations.AlterField(
            model_name='tokendata',
            name='tokenid',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Token ID'),
        ),
        migrations.AlterField(
            model_name='useraccountdata',
            name='apikey',
            field=models.CharField(max_length=100, verbose_name='Api Key'),
        ),
        migrations.AlterField(
            model_name='useraccountdata',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date Created'),
        ),
        migrations.AlterField(
            model_name='useraccountdata',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email Address'),
        ),
        migrations.AlterField(
            model_name='useraccountdata',
            name='fullname',
            field=models.CharField(max_length=50, verbose_name='Full Name'),
        ),
        migrations.AlterField(
            model_name='useraccountdata',
            name='password',
            field=models.CharField(max_length=15, verbose_name='Password'),
        ),
        migrations.AlterField(
            model_name='useraccountdata',
            name='phonenumber',
            field=models.CharField(blank=True, max_length=15, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='useraccountdata',
            name='userid',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='User ID'),
        ),
        migrations.AlterField(
            model_name='venuedata',
            name='OSMID',
            field=models.CharField(blank=True, max_length=100, verbose_name='OSM ID'),
        ),
        migrations.AlterField(
            model_name='venuedata',
            name='capacity',
            field=models.IntegerField(verbose_name='Venue Capacity'),
        ),
        migrations.AlterField(
            model_name='venuedata',
            name='city',
            field=models.CharField(max_length=100, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='venuedata',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date Created'),
        ),
        migrations.AlterField(
            model_name='venuedata',
            name='description',
            field=models.CharField(blank=True, max_length=150, verbose_name='Venue Description'),
        ),
        migrations.AlterField(
            model_name='venuedata',
            name='googleplacesId',
            field=models.CharField(blank=True, max_length=100, verbose_name='Google Place ID'),
        ),
        migrations.AlterField(
            model_name='venuedata',
            name='hits',
            field=models.IntegerField(verbose_name='Hits'),
        ),
        migrations.AlterField(
            model_name='venuedata',
            name='loc_lat',
            field=models.CharField(blank=True, max_length=20, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='venuedata',
            name='loc_lng',
            field=models.CharField(blank=True, max_length=20, verbose_name='Longitude'),
        ),
        migrations.RemoveField(
            model_name='venuedata',
            name='menu',
        ),
        migrations.AlterField(
            model_name='venuedata',
            name='micro_brewery',
            field=models.BooleanField(default=False, verbose_name='Micro Brewery'),
        ),
        migrations.AlterField(
            model_name='venuedata',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Venue Name'),
        ),
        migrations.AlterField(
            model_name='venuedata',
            name='neighborhood',
            field=models.CharField(blank=True, max_length=100, verbose_name='Neighborhood'),
        ),
        migrations.AlterField(
            model_name='venuedata',
            name='open_now',
            field=models.BooleanField(default=False, verbose_name='Open Now'),
        ),
        migrations.AlterField(
            model_name='venuedata',
            name='open_periods',
            field=django.contrib.postgres.fields.jsonb.JSONField(verbose_name='Open Periods'),
        ),
        migrations.AlterField(
            model_name='venuedata',
            name='outdoorsitting',
            field=models.BooleanField(default=False, verbose_name='Outdoor Sitting'),
        ),
        migrations.AlterField(
            model_name='venuedata',
            name='phonenumber',
            field=models.CharField(max_length=20, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='venuedata',
            name='postcode',
            field=models.CharField(max_length=100, verbose_name='Post Code'),
        ),
        migrations.AlterField(
            model_name='venuedata',
            name='price_start',
            field=models.CharField(blank=True, max_length=100, verbose_name='Start Price'),
        ),
        migrations.AlterField(
            model_name='venuedata',
            name='smookingavailability',
            field=models.BooleanField(default=False, verbose_name='Smooking Availability'),
        ),
        migrations.AlterField(
            model_name='venuedata',
            name='streetname',
            field=models.CharField(max_length=100, verbose_name='Street Name'),
        ),
        migrations.RemoveField(
            model_name='venuedata',
            name='type',
        ),
        migrations.AlterField(
            model_name='venuedata',
            name='venueid',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Venue ID'),
        ),
        migrations.AlterField(
            model_name='venuedata',
            name='website',
            field=models.CharField(blank=True, max_length=200, verbose_name='Website Address'),
        ),
        migrations.AlterField(
            model_name='venuedata',
            name='wheelchairavail',
            field=models.BooleanField(default=False, verbose_name='Wheel Chair Availability'),
        ),
        migrations.AddField(
            model_name='openhours',
            name='venue',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='restapi.VenueData', verbose_name='Venue'),
        ),
        migrations.AddField(
            model_name='venuedata',
            name='activities',
            field=models.ManyToManyField(help_text='Select activities for this Venue', to='restapi.ActivityData'),
        ),
        migrations.AddField(
            model_name='venuedata',
            name='menu',
            field=models.ManyToManyField(help_text='Select menu for this venue', to='restapi.MenuData'),
        ),
        migrations.AddField(
            model_name='venuedata',
            name='type',
            field=models.ManyToManyField(help_text='Select venue type', to='restapi.VenueTypeData'),
        ),
    ]
