# Generated by Django 2.0.7 on 2018-08-17 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0007_auto_20180817_1200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venuedata',
            name='open_now',
        ),
        migrations.RemoveField(
            model_name='venuedata',
            name='open_periods',
        ),
        migrations.AddField(
            model_name='venuedata',
            name='managername',
            field=models.CharField(blank=True, max_length=25500, verbose_name="Managers' Name"),
        ),
        migrations.AddField(
            model_name='venuedata',
            name='verified',
            field=models.BooleanField(default=False, verbose_name='Verified'),
        ),
    ]
