# Generated by Django 2.0.7 on 2018-08-17 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0008_auto_20180817_1332'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menudata',
            options={'ordering': ('menuid',), 'verbose_name_plural': 'Menu Types'},
        ),
        migrations.AlterModelOptions(
            name='openhours',
            options={'ordering': ('days',), 'verbose_name_plural': 'Opening hours'},
        ),
        migrations.RemoveField(
            model_name='openhours',
            name='venue',
        ),
        migrations.AddField(
            model_name='venuedata',
            name='openperiods',
            field=models.ManyToManyField(help_text='Select opening periods', to='restapi.OpenHours'),
        ),
        migrations.AlterField(
            model_name='openhours',
            name='days',
            field=models.CharField(choices=[('0', 'SUNDAY'), ('1', 'MONDAY'), ('2', 'TUESDAY'), ('3', 'WEDNESDAY'), ('4', 'THURSDAY'), ('5', 'FRIDAY'), ('6', 'SATURDAY')], max_length=10, verbose_name='Day of week'),
        ),
        migrations.AlterField(
            model_name='venuedata',
            name='verified',
            field=models.BooleanField(default=False, verbose_name='Verified by Administrator'),
        ),
    ]
